
@Restaurants.API_HostAddress = https://localhost:7028

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/0e00d22d-d7d9-45d4-a521-068849bb9669

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{709d04c5-a5e0-4392-b5cf-295b5ce08e45}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Ta"
}


###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{709d04c5-a5e0-4392-b5cf-295b5ce08e45}
Content-Type: application/json

{
  "Name": "NewName",
  "Description": "NewDesc",
  "HasDelivery": false
}

###
